// var words = ["She's feeling a bit tired after the long hike.","There are only a few apples left in the basket."];


var words = [
"She's feeling a bit tired after the long hike.",
"There are only a few apples left in the basket.",
"Could you add a little sugar to my tea, please?",
"A group of tourists gathered around the guide to listen to the history of the monument.",
"That bird is a kind of sparrow commonly found in this area.",
"There were a lot of people at the concert last night.",
"A number of students have already completed their assignments.",
"She bought a pair of new shoes for the party.",
"Can you pass me a piece of paper, please?",
"According to the weather forecast, it's going to rain tomorrow.",
"Let's meet up after class to work on the group project.",
"They usually play soccer together after school.",
"I agree with you on that decision.",
"He kept making the same mistake again and again.",
"The news of their engagement spread all over the town.",
"Are you feeling all right after the accident?",
"Wishing you all the best in your new job!",
"He talks about his travels all the time.",
"We walked all the way to the top of the mountain.",
"She likes to read mystery novels, thrillers, and so on.",
"He apologized to his friend for being late.",
"We arrived at the airport just in time for our flight.",
"I'll have the burger as well, please.",
"He asked for help when he couldn't solve the problem.",
"We usually have cereal at breakfast.",
"At first, I didn't like the movie, but it grew on me.",
"She prefers to study at home rather than in the library.",
"You should brush your teeth at least twice a day.",
"Please submit your report at once.",
"What did you learn at school today?",
"I'm busy at the moment, can I call you back later?",
"She can cook dinner and talk on the phone at the same time.",
"He's at work right now, so he can't answer the phone.",
"I like to go hiking at the weekends.",
"With enough practice, you'll be able to play the guitar well.",
"Some people are afraid of spiders.",
"She's still angry with her sister for breaking her favorite mug.",
"Smoking is bad for your health.",
"He was born in Paris but grew up in London.",
"She's busy with her studies right now.",
"Be careful with that glass vase; it's fragile.",
"The table was covered with a white tablecloth for the dinner party.",
"My tastes are different from yours.",
"The song sounded familiar to me, but I couldn't remember the title.",
"Italy is famous for its delicious cuisine.",
"She's fond of reading detective novels in her free time.",
"The room was full of laughter and chatter during the party.",
"She's good at playing the piano but poor at dancing.",
"He's always been interested in astronomy.",
"She's keen on learning new languages.",
"Don't be late for the meeting; it starts in ten minutes.",
"The hotel is located in the heart of the city.",
"This table is made of solid oak wood.",
"The committee is made up of volunteers from the community.",
"The new movie will be on at the cinema this weekend.",
"She was pleased with the results of her hard work.",
"I'm proud of my sister for graduating with honors.",
"We need to get ready for the big presentation tomorrow.",
"She was surprised at how quickly the time passed.",
"I'm thankful to my parents for their support throughout my education.",
"It took me a while to get used to waking up early for work.",
"She's worried about her upcoming exams.",
"The event was canceled because of the bad weather.",
"This book belongs to my sister.",
"A fire broke out in the kitchen last night.",
"Someone tried to break into our house last week.",
"I sent the documents by air mail to ensure they arrive quickly.",
"Let's go to the city center by bus.",
"She painted the entire house by herself.",
"You can reach me by phone if you need anything.",
"By the way, have you seen my keys?",
"We decided to call on our neighbors to introduce ourselves.",
"She cares for her sick grandmother every weekend.",
"The researchers plan to carry out experiments to test their hypothesis.",
"Be careful not to catch a cold in this chilly weather.",
"I need to catch up with my classmates in math.",
"After listening to the arguments, he decided to change his mind about the proposal.",
"Passengers must check in at least two hours before their flight.",
"I came across an interesting article while browsing the internet.",
"I'll come back to your question in a moment.",
"She comes from a small town in the Midwest.",
"Come on, let's go for a walk in the park.",
"Her new book will come out next month.",
"The concert came to an end with a spectacular fireworks display.",
"Through his travels, he came to know many different cultures.",
"The garden comes to life in the spring with colorful flowers.",
"Her dream of traveling around the world finally came true.",
"She struggled to come up with a solution to the problem.",
"We can communicate with each other through email.",
"This hotel room compares well with the one we stayed in last time.",
"We congratulated him on his promotion.",
"The park covers an area of 100 acres.",
"We need to cut down on our expenses to save money.",
"She knows how to deal with difficult customers effectively.",
"Your success will depend on your hard work and dedication.",
"Many people died of starvation during the famine.",
"His approach to problem-solving is different from mine.",
"Even though it was difficult, she did her best to complete the project on time.",
"Can you do me a favor and pick up my dry cleaning?",
"Let's do some shopping at the mall this weekend.","do with: We need to decide what to do with the old furniture.",
  "dream of: As a child, she often dreamt of becoming a pilot.",
  "dress up: Let's dress up for the costume party tonight.",
  "each other: They looked at each other and smiled.",
  "eat up: The kids ate up all the cookies in no time.",
  "earn one’s life: He works hard to earn his life as a freelance writer.",
  "either… or…: You can either go to the concert with me or stay home.",
  "enjoy oneself: I hope you enjoy yourself at the party tonight.",
  "enter for: She decided to enter for the photography competition.",
  "even if / though: Even if it rains, we'll still go camping.",
  "fall off: The leaf fell off the tree and drifted to the ground.",
  "far away (from): The beach is far away from our hotel.",
  "far from: His behavior is far from acceptable.",
  "feel like doing: I feel like going for a walk in the park.",
  "fill in: Please fill in the form with your personal details.",
  "fill … with …: She filled the room with beautiful flowers for the party.",
  "find out: I need to find out the time of the train departure.",
  "finish off: He finished off the last piece of cake with a satisfied smile.",
  "first of all: First of all, let's address the most pressing issue.",
  "for ever: Their love seemed to last for ever.",
  "for example: There are many delicious fruits, for example, apples, oranges, and bananas.",
  "for the first time: She visited Paris for the first time last summer.",
  "for the time being: Let's leave the problem for the time being and focus on what we can control.",
  "from … to…: The store is open from Monday to Friday, from 9 a.m. to 6 p.m.",
  "from door to door: The salesman went from door to door selling vacuum cleaners.",
  "from now on: From now on, I'll start saving money for my future.",
  "from time to time: She visits her grandparents from time to time.",
  "get along / on (with): He gets along well with his coworkers.",
  "go away: The annoying noise wouldn't go away, no matter what they did.",
  "get back: I'll get back to you with the information as soon as possible.",
  "get in: Let's get in the car and go for a drive.",
  "get in the way: Please move your backpack; it's getting in the way.",
  "get off: We need to get off at the next stop.",
  "get on: We got on the train just before it departed.",
  "get on with: I get on well with my neighbors.",
  "get ready for: She's getting ready for her big presentation tomorrow.",
  "get rid of: He needs to get rid of all the junk in his garage.",
  "get tired of: I'm getting tired of eating the same thing for dinner every night.",
  "get to: We finally got to the top of the mountain after hours of hiking.",
  "get together: Let's get together for a barbecue this weekend.",
  "get up: I usually get up early to go for a run.",
  "give back: Don't forget to give back the books you borrowed from the library.",
  "give out: She gave out pamphlets to passersby on the street.",
  "give sb. a hand: Can you give me a hand with carrying these groceries?",
  "give up: Don't give up on your dreams, keep working towards them.",
  "go ahead: If you're ready, you can go ahead and start the presentation.",
  "go away: The dog went away after being shooed off the lawn.",
  "go shopping / bowling: Let's go shopping this afternoon.",
  "go for a swim: It's so hot today; let's go for a swim at the beach.",
  "go for a walk: After dinner, they like to go for a walk around the neighborhood.",
  "go home: It's getting late; let's go home.",
  "go in for: She decided to go in for swimming as her new hobby.",
  "go on: The show must go on, despite the technical difficulties.",
  "go on a diet: She decided to go on a diet to lose weight before her wedding.",
  "go on a picnic: We're planning to go on a picnic next weekend if the weather is nice.",
  "go on with / doing sth: Despite the interruption, she went on with her presentation.",
  "go out: The lights went out during the storm.",
  "go over: Let's go over the details of the plan one more time.",
  "go sightseeing: They went sightseeing in Paris and visited all the famous landmarks.",
  "go to (the) hospital: She had to go to the hospital for a check-up.",
  "go to bed: It's getting late; it's time to go to bed.",
  "go to college: After high school, she decided to go to college to study biology.",
  "go to school: The kids go to school by bus every morning.",
  "go to sleep: After a long day, she quickly fell asleep.",
  "go to the cinema / movie(s): Let's go to the cinema tonight to watch the latest blockbuster.",
  "go up: The price of gasoline has gone up again.",
  "go wrong: Something went wrong with the experiment, and we'll need to start over.",
  "grow up: When I grow up, I want to be a doctor.",
  "had better: You had better hurry if you don't want to miss the bus.",
  "hand in: Don't forget to hand in your assignments before the deadline.",
  "hand out: The teacher handed out worksheets to the students.",
  "happen to do: I happened to meet an old friend at the supermarket yesterday.",
  "happen to sb: It happened to her that she lost her wallet on the way home.",
  "have fun with: The kids had fun with their new toys at the playground.",
  "have fun doing: She always has fun singing karaoke with her friends.",
  "have (got) to: I have to finish this report before the end of the day.",
  "have a class / lesson: I have a class in the morning, so I can't meet you for breakfast.",
  "have a good time: Did you have a good time at the party last night?",
  "have breakfast: They usually have breakfast together as a family on weekends.",
  "have no idea: I have no idea where I left my keys.",
  "have sports: Many schools have sports programs to encourage physical activity among students.",
  "hear from: I haven't heard from my friend in a long time; I wonder how he's doing.",
  "hear of: Have you heard of the new restaurant that opened downtown?",
  "help sb. with sth: Can you help me with my math homework?",
  "help oneself to …: Please help yourself to some snacks on the table.",
  "here and there: She scattered the decorations here and there around the room.",
  "hold a meeting: The company will hold a meeting to discuss the new project tomorrow.",
  "hold on: Can you hold on for a moment? I'll be right back.",
  "hold one's breath: She held her breath as she waited for the final exam results.",
  "hold up: The bridge held up despite the heavy traffic.",
  "huge amounts of: The factory produces huge amounts of plastic waste every year.",
  "hundreds of: There are hundreds of people waiting in line for tickets to the concert.",
  "hurry off: He hurried off to catch the last train home.",
  "hurry up: Hurry up, or we'll be late for the movie!",
  "in a hurry: She left the house in a hurry, forgetting her keys on the kitchen counter.",
  "in a minute: I'll be with you in a minute; I just need to finish this email.",
  "in a word: In a word, the presentation was excellent.",
  "in addition: In addition to his regular job, he also volunteers at the local shelter.",
  "in all: There are ten apples in all; five green ones and five red ones.",
  "in charge of: She's in charge of managing the marketing department.","She's feeling a bit tired after the long hike.","There are only a few apples left in the basket.", "She's in danger of falling off the cliff if she's not careful.", "The meeting will be conducted in English for the international participants.", "It wasn't a dog; in fact, it was a wolf.", "Please wait for me in front of the store.", "She's currently in hospital recovering from surgery.", "Please stand in line and wait for your turn.", "With her efficient work ethic, she completed the project in no time.", "He started learning to play the guitar in his fifties.", "In my opinion, the best option is to go with the blue design.", "The files need to be arranged in order by date.", "He studied hard in order to pass the exam.", "She's an introvert, in other words, she prefers quiet environments.", "He helped them, and in return, they offered their assistance.", "She looked at him in surprise when he announced the news.", "It's impolite to argue in public.", "She gasped in surprise when she saw the unexpected guest.", "In the end, they decided to go with the original plan.", "In the future, we hope to expand our business internationally.", "He was in the middle of a meeting when his phone rang.", "In the years to come, technology will continue to advance rapidly.", "By saving money regularly, you can build up your savings in this way.", "They arrived just in time for the concert.", "She chose tea instead of coffee for her morning beverage.", "He's always getting into trouble for not completing his homework.", "Let's take the stairs instead of the elevator to get some exercise.", "Everyone is welcome to join in the festivities.", "Wait just a minute; I'll be right back with your order.", "I saw her leaving just now; she must be in a hurry.", "If you keep practicing, you'll improve your skills.", "She goes to the gym regularly to keep fit.", "It's important to keep one's word to maintain trust in relationships.", "She kept her children from playing outside in the rain.", "Even though they live far apart, they keep in touch through regular phone calls.", "Please keep off the freshly painted bench.", "During the exam, everyone must keep quiet.", "The new project kept him busy all week.", "Be careful not to knock over the vase on the table.", "We can discuss this matter later on when we have more time.", "It's not polite to laugh at someone's mistakes.", "Please lay the table for dinner; we're expecting guests.", "We should learn from our mistakes to avoid repeating them in the future.", "After leaving secondary school, he pursued a career in engineering.", "If I'm not available, please leave a message, and I'll get back to you as soon as possible.", "They're leaving for their vacation tomorrow morning.", "She has less than ten minutes to finish the exam.", "The teacher let out the class early because of the heat.", "Please line up in an orderly fashion to enter the theater.", "He likes to listen to classical music while studying.", "After retirement, they had to live on a fixed income.", "She looks after her younger siblings while her parents are at work.", "It's not right to look down upon people who are less fortunate than you.", "Look at this beautiful sunset; it's breathtaking.", "I'm looking for my keys; have you seen them anywhere?", "I look forward to meeting you next week.", "She looks like her mother; they have the same eyes.", "He looked out of the window and saw the rain pouring down.", "If you don't know the meaning of a word, you can look it up in the dictionary.", "They lost their way in the forest and had to rely on a map to find their way back.", "She started exercising regularly to lose weight.", "He made a funny face to make his little sister laugh.", "The director decided to make a film based on the bestselling novel.", "We gathered wood and kindling to make a fire while camping in the woods.", "He works as a freelance writer to make a living.", "It's okay to make a mistake as long as you learn from it.", "Please don't make a noise; I'm trying to concentrate.", "He moved to a new city and made friends with his neighbors quickly.", "It's not nice to make fun of someone's appearance.", "Many people invest in the stock market to make money.", "Every morning, she makes her bed before starting her day.", "In the darkness, it was difficult to make out what was ahead of us.", "With consistent practice, you'll make progress in learning a new language.", "After much deliberation, she finally made up her mind about which college to attend.", "The new restaurant aims to meet the needs of vegetarian customers with its diverse menu.", "He met with unexpected challenges while implementing the new project.", "The project is more or less finished; we just need to do some final touches.", "Neither the blue dress nor the green one fits me properly.", "The bookstore is located next to the coffee shop.", "He's no longer interested in playing video games.", "I'm not hungry at all; I just ate a big meal.", "She is not only intelligent but also kind-hearted.", "She's not so tall as her sister.", "I didn't realize how serious it was not until I heard the news.", "Now and then, she likes to take a break and go for a walk.", "Of course," she said with a smile, "I'd be happy to help.", "She wanted a room of her own where she could study in peace.", "He travels frequently on business trips to different countries.", "The security guard is always on duty, monitoring the premises.", "We explored the city on foot to see all the sights.", "She's on holiday for two weeks, relaxing at the beach.", "I'll always be on your side, no matter what happens.", "Her artwork will be on show at the gallery next week.", "On the one hand, it's expensive, but on the other hand, it's high quality.", "He's busy on the phone right now; can I take a message?", "The restaurant is on the right, just after the traffic light.", "I'm on my way to the store; I'll be there in ten minutes.", "The train arrived on time, and we boarded without any delays.", "On weekdays, she works long hours at the office.", "The doctor prescribed taking the medication once a day with food.", "Once again, she apologized for the misunderstanding.", "The Olympic Games occur once every four years."];