/*
var words = [
  "bless you",
  "either of",
  "a bit (of)",
  "a few",
  "a little",
  "a group of",
  "a kind of",
  "a lot of (lots of)",
  "a number of",
  "a pair of",
  "a piece of",
  "according to",
  "after class",
  "after school",
  "agree with sb/ to+V.",
  "again and again",
  "all over",
  "all right",
  "all the best",
  "all the time",
  "all the way",
  "and so on",
  "apologize to sb. for sth.",
  "arrive at / in a place",
  "as well",
  "ask for",
  "at breakfast /lunch /supper",
  "at first / last",
  "at home",
  "at least / most",
  "at once",
  "at school",
  "at the moment",
  "at the same time",
  "at work",
  "at the / on weekends",
  "be able to",
  "be afraid of",
  "be angry with sb.",
  "be bad for",
  "be born",
  "be busy with / doing sth.",
  "be careful with",
  "be covered with",
  "be different from",
  "be familiar to",
  "be famous for",
  "be fond of",
  "be full of",
  "be good / poor at",
  "be interested in",
  "be keen on",
  "be late for",
  "be located (in/on/at)",
  "be made of",
  "be made up of",
  "be on",
  "be pleased with",
  "be proud of",
  "be/get ready for",
  "be surprised at",
  "be thankful to sb.",
  "be/get used to＋v－ing",
  "be worried/serious about",
  "because of=thanks to",
  "belong to",
  "break out",
  "break into",
  "by air mail",
  "by bus",
  "by oneself",
  "by phone",
  "by the way",
  "call on",
  "care for",
  "carry out",
  "catch (a) cold",
  "catch up with",
  "change one's mind",
  "check in",
  "come across",
  "come back",
  "come from",
  "come on",
  "come out",
  "come to an end",
  "come to know",
  "come to life",
  "come true",
  "come up with",
  "communicate with",
  "compare with",
  "congratulate …on…",
  "cover an area of",
  "cut down",
  "deal with",
  "depend on",
  "die of",
  "different from",
  "do one's best",
  "do sb. a favour",
  "do some shopping",
  "do with",
  "dream of",
  "dress up",
  "each other",
  "eat up",
  "earn one’s life",
  "either… or…",
  "enjoy oneself",
  "enter for",
  "even if / though",
  "fall off",
  "far away (from)",
  "far from",
  "feel like doing",
  "fill in",
  "fill … with …",
  "find out",
  "finish off",
  "first of all",
  "for ever",
  "for example",
  "for the first time",
  "for the time being",
  "from … to…",
  "from door to door",
  "from now on",
  "from time to time",
  "get along / on (with)",
  "go away",
  "get back",
  "get in",
  "get in the way",
  "get off",
  "get on",
  "get on with",
  "get ready for",
  "get rid of",
  "get tired of",
  "get to",
  "get together",
  "get up",
  "give back",
  "give out",
  "give sb. a hand",
  "give up",
  "go ahead",
  "go shopping / bowling",
  "go for a swim",
  "go for a walk",
  "go home",
  "go in for",
  "go on",
  "go on a diet",
  "go on a picnic",
  "go on with / doing sth.",
  "go out",
  "go over",
  "go sightseeing",
  "go to (the) hospital",
  "go to bed",
  "go to college",
  "go to school",
  "go to sleep",
  "go to the cinema / movie(s)",
  "go up",
  "go wrong",
  "grow up",
  "had better",
  "hand in",
  "hand out",
  "happen to do",
  "happen to sb.",
  "have fun with",
  "have fun doing",
  "have (got) to",
  "have a class / lesson",
  "have a good time",
  "have breakfast",
  "have no idea",
  "have pity on sb.",
  "have sports",
  "hear from",
  "hear of",
  "help sb. with sth.",
  "help oneself to …",
  "here and there",
  "hold a meeting",
  "hold on",
  "hold one's breath",
  "hold up",
  "huge amounts of",
  "hundreds of",
  "hurry off",
  "hurry up",
  "in a hurry",
  "in a minute",
  "in a word",
  "in addition",
  "in all",
  "in charge of",
  "in danger",
  "in English",
  "in fact",
  "in front of",
  "in hospital",
  "in line",
  "in no time",
  "in one's fifties",
  "in one's opinion",
  "in order",
  "in order to",
  "in other words",
  "in return",
  "in surprise",
  "in public",
  "in the end",
  "in the future",
  "in the middle of",
  "in the years to come",
  "in this way",
  "in time",
  "instead of",
  "in trouble",
  "join in",
  "just a minute",
  "just now",
  "keep doing sth.",
  "keep fit",
  "keep one's word",
  "keep... from",
  "keep in touch (with)",
  "keep off",
  "keep quiet",
  "keep sb. busy",
  "knock over",
  "later on",
  "laugh at",
  "lay the table",
  "learn…from",
  "leave (secondary) school",
  "leave a message",
  "leave for",
  "less / more than",
  "let out",
  "line up",
  "listen to",
  "live on",
  "look after",
  "look down upon",
  "look at",
  "look for",
  "look forward to+V-ing",
  "look like",
  "look out of",
  "look up",
  "lose one's way",
  "lose weight",
  "make a face",
  "make a film",
  "make a fire",
  "make a living",
  "make a mistake",
  "make a noise",
  "make friends with",
  "make fun of",
  "make money",
  "make the/one's bed",
  "make out",
  "make progress",
  "make up one's mind",
  "meet the needs of",
  "meet with",
  "more or less",
  "neither… nor…",
  "next to",
  "no longer / not …any more/longer",
  "not…at all",
  "not only …but also…",
  "not so…as",
  "not till / until",
  "now and then /again",
  "of course",
  "of one's own",
  "on business",
  "on duty",
  "on foot",
  "on holiday",
  "on one's side",
  "on show",
  "on the other hand",
  "on the phone",
  "on the right",
  "on the/one's way (to)",
  "on time",
  "on weekdays",
  "once a day",
  "once again",
  "once every four years",
  "once more",
  "once upon a time",
  "one after another",
  "one another",
  "operate on sb.",
  "out of",
  "out of work",
  "out of date",
  "over and over",
  "over there",
  "pass by",
  "pay for",
  "pick out",
  "pick up",
  "play a trick on",
  "play with",
  "plenty of",
  "point at",
  "point out",
  "praise sb. for sth.",
  "prefer...to",
  "prepare for",
  "protect...from",
  "prevent ...from",
  "pull down",
  "put down",
  "put off",
  "put on",
  "put out",
  "put up",
  "rely on",
  "right now",
  "ring up",
  "run after",
  "run away",
  "run out of",
  "save one's life",
  "search for",
  "see...off",
  "sell out",
  "send for",
  "separate ... from",
  "set free",
  "set off",
  "set out",
  "show off",
  "so far",
  "so...that",
  "sooner or later",
  "speed up",
  "spend ...on",
  "stand for",
  "stop doing sth.",
  "stop to do sth.",
  "such as",
  "take away",
  "take it easy",
  "take off",
  "take one's time",
  "take out",
  "take place",
  "talk about",
  "the day after tomorrow",
  "the day before yesterday",
  "the more...the more",
  "the other day",
  "think about",
  "think of",
  "thousands of",
  "throw away",
  "too...to",
  "try on",
  "try out",
  "turn down",
  "turn off"*/
];
*/

var words = [
    "She's feeling a bit tired after the long hike.",
    "There are only a few apples left in the basket.",
    "Could you add a little sugar to my tea, please?",
    "A group of tourists gathered around the guide to listen to the history of the monument.",
    "That bird is a kind of sparrow commonly found in this area.",
    "There were a lot of people at the concert last night.",
    "A number of students have already completed their assignments.",
    "She bought a pair of new shoes for the party.",
    "Can you pass me a piece of paper, please?",
    "According to the weather forecast, it's going to rain tomorrow.",
    "Let's meet up after class to work on the group project.",
    "They usually play soccer together after school.",
    "I agree with you on that decision.",
    "He kept making the same mistake again and again.",
    "The news of their engagement spread all over the town.",
    "Are you feeling all right after the accident?",
    "Wishing you all the best in your new job!",
    "He talks about his travels all the time.",
    "We walked all the way to the top of the mountain.",
    "She likes to read mystery novels, thrillers, and so on.",
    "He apologized to his friend for being late.",
    "We arrived at the airport just in time for our flight.",
    "I'll have the burger as well, please.",
    "He asked for help when he couldn't solve the problem.",
    "We usually have cereal at breakfast.",
    "At first, I didn't like the movie, but it grew on me.",
    "She prefers to study at home rather than in the library.",
    "You should brush your teeth at least twice a day.",
    "Please submit your report at once.",
    "What did you learn at school today?",
    "I'm busy at the moment, can I call you back later?",
    "She can cook dinner and talk on the phone at the same time.",
    "He's at work right now, so he can't answer the phone.",
    "I like to go hiking at the weekends.",
    "With enough practice, you'll be able to play the guitar well.",
    "Some people are afraid of spiders.",
    "She's still angry with her sister for breaking her favorite mug.",
    "Smoking is bad for your health.",
    "He was born in Paris but grew up in London.",
    "She's busy with her studies right now.",
    "Be careful with that glass vase; it's fragile.",
    "The table was covered with a white tablecloth for the dinner party.",
    "My tastes are different from yours.",
    "The song sounded familiar to me, but I couldn't remember the title.",
    "Italy is famous for its delicious cuisine.",
    "She's fond of reading detective novels in her free time.",
    "The room was full of laughter and chatter during the party.",
    "She's good at playing the piano but poor at dancing.",
    "He's always been interested in astronomy.",
    "She's keen on learning new languages.",
    "Don't be late for the meeting; it starts in ten minutes.",
    "The hotel is located in the heart of the city.",
    "This table is made of solid oak wood.",
    "The committee is made up of volunteers from the community.",
    "The new movie will be on at the cinema this weekend.",
    "She was pleased with the results of her hard work.",
    "I'm proud of my sister for graduating with honors.",
    "We need to get ready for the big presentation tomorrow.",
    "She was surprised at how quickly the time passed.",
    "I'm thankful to my parents for their support throughout my education.",
    "It took me a while to get used to waking up early for work.",
    "She's worried about her upcoming exams.",
    "The event was canceled because of the bad weather.",
    "This book belongs to my sister.",
    "A fire broke out in the kitchen last night.",
    "Someone tried to break into our house last week.",
    "I sent the documents by air mail to ensure they arrive quickly.",
    "Let's go to the city center by bus.",
    "She painted the entire house by herself.",
    "You can reach me by phone if you need anything.",
    "By the way, have you seen my keys?",
    "We decided to call on our neighbors to introduce ourselves.",
    "She cares for her sick grandmother every weekend.",
    "The researchers plan to carry out experiments to test their hypothesis.",
    "Be careful not to catch a cold in this chilly weather.",
    "I need to catch up with my classmates in math.",
    "After listening to the arguments, he decided to change his mind about the proposal.",
    "Passengers must check in at least two hours before their flight.",
    "I came across an interesting article while browsing the internet.",
    "I'll come back to your question in a moment.",
    "She comes from a small town in the Midwest.",
    "Come on, let's go for a walk in the park.",
    "Her new book will come out next month.",
    "The concert came to an end with a spectacular fireworks display.",
    "Through his travels, he came to know many different cultures.",
    "The garden comes to life in the spring with colorful flowers.",
    "Her dream of traveling around the world finally came true.",
    "She struggled to come up with a solution to the problem.",
    "We can communicate with each other through email.",
    "This hotel room compares well with the one we stayed in last time.",
    "We congratulated him on his promotion.",
    "The park covers an area of 100 acres.",
    "We need to cut down on our expenses to save money.",
    "She knows how to deal with difficult customers effectively.",
    "Your success will depend on your hard work and dedication.",
    "Many people died of starvation during the famine.",
    "His approach to problem-solving is different from mine.",
    "Even though it was difficult, she did her best to complete the project on time.",
    "Can you do me a favor and pick up my dry cleaning?",
    "Let's do some shopping at the mall this weekend."
];