var words = [
"a few: I have a few books to return to the library.",
"a few minutes: Can you wait for me? I'll be ready in a few minutes.",
"a few times: I've tried to solve this puzzle a few times, but I still can't figure it out.",
"a few years: We lived in that house for a few years before moving to a new city.",
"a good idea: Joining a gym is a good idea for improving your fitness.",
"Good idea!: Let's go for a hike instead of staying indoors. Good idea!",
"It’s a good idea to…: It's a good idea to double-check your work before submitting it.",
"That’s a good idea!: Let's have a picnic in the park. That's a good idea!",
"agree with sb: I agree with you on that decision.",
"a little: Could you add a little more salt to the soup?",
"a little help: Can you give me a little help with this heavy box?",
"a little money: I have saved up a little money for our vacation.",
"a little sugar: Can you please pass me a little sugar for my coffee?",
"a lot: There is a lot of traffic on the highway today.",
"a lot to do: I have a lot to do before the deadline.",
"a lot of sth: She has a lot of friends in the neighborhood.",
"all day: I've been studying all day for my exam tomorrow.",
"all night: The party lasted all night, and we didn't get much sleep.",
"all over the world: Pizza is enjoyed by people all over the world.",
"anything else: Is there anything else I can assist you with?",
"anyone else: Did anyone else see what happened?",
"a period of time: He spent a long period of time traveling through Asia.",
"around the world: She dreams of traveling around the world one day.",
"arrive at…: What time did you arrive at the airport?",
"arrive in…: They are expected to arrive in Paris tomorrow morning.",
"ask for sth: Don't be afraid to ask for help if you need it.",
"at home: I feel most comfortable when I'm at home.",
"at school: Students are expected to be on time at school.",
"at the beginning of sth: At the beginning of the movie, the main character faces a dilemma.",
"at the end: I always cry at the end of sad movies.",
"at the end of sth: At the end of the day, it's important to relax and unwind.",
"at the moment: Sorry, I can't talk right now; I'm busy at the moment.",
"at the same time: It's hard to focus on two tasks at the same time.",
"at the weekend: We usually go hiking at the weekend.",
"at university: She's studying psychology at university.",
"at work: I'm usually very busy at work, so I rarely have time to relax.",
"away from sb/sth: He moved away from his hometown to pursue better opportunities.",
"bad for sb/sth: Eating too much junk food is bad for your health.",
"bad news: I'm sorry to be the bearer of bad news, but the event has been canceled.",
"bad thing: Losing your temper is always a bad thing.",
"the bad things about sth: One of the bad things about living in a big city is the pollution.",
"because of: The flight was delayed because of bad weather.",
"begin with sth: Let's begin with a warm-up exercise before starting the main workout.",
"be going to do sth: I'm going to bake a cake for my sister's birthday.",
"best friend: Sarah has been my best friend since we were in kindergarten.",
"black and white: The old photograph was in black and white, capturing a moment from the past.",
"car park: The car park was full, so I had to find parking on the street.",
"cell phone: Don't forget to bring your cell phone with you in case of an emergency.",
"city centre: We're meeting at the café in the city center at noon.",
"in the city centre: The new shopping mall is located right in the city center.",
"come from…: She comes from a small town in the Midwest.",
"come into sth: He came into the room and immediately noticed the mess.",
"- *She went into her room*.",
"differences between A and B: Can you explain the differences between these two models?",
"difficult for sb: Learning a new language can be difficult for some people.",
"it is difficult for sb to do sth: It is difficult for beginners to master advanced techniques.",
"each other: We should respect and help each other in times of need.",
"end in sth: The story ends in a surprising twist.",
"every day: I go for a run every day to stay healthy.",
"every week: We have a team meeting every week to discuss our progress.",
"every year: My family goes on vacation to the beach every year.",
"excuse me: Excuse me, do you know where the nearest restroom is?",
"family member: She is my favorite family member.",
"find out: I need to find out what time the movie starts.",
"find out about sth: I finally found out about the surprise party they were planning for me.",
"find out more: If you want to learn more about our company, visit our website.",
"for a long time: They have been friends for a long time.",
"a long time: It took a long time to finish the project.",
"for a moment: Could you wait here for a moment while I grab my coat?",
"for example: There are many reasons to exercise regularly, for example, to improve your health.",
"for lunch: Let's meet for lunch tomorrow at noon.",
"for many years: They have lived in that house for many years.",
"for the first time: She traveled abroad for the first time last summer.",
"get home: I can't wait to get home and relax after a long day at work.",
"get married: They are getting married next month in a beautiful ceremony.",
"get off: I'll get off the train at the next station.",
"get off the bus: We need to get off the bus at the next stop.",
"get on: Make sure to get on the train before it departs.",
"get on the bus: Make sure to get on the bus before it leaves.",
"Are you getting on?: Are you getting on the train with us?",
"get ready: I need to get ready for the party tonight.",
"get ready for sth: Get ready for a fun-filled day at the amusement park.",
"get ready to do sth: Get ready to experience the adventure of a lifetime.",
"get there: Don't worry; we'll get there on time.",
"get to…: We finally got to the top of the mountain after hours of hiking.",
"get up: I usually get up at 7 a.m. on weekdays.",
"go back: I need to go back to the store to return this item.",
"go back to…: He decided to go back to school to pursue a degree in engineering.",
"go home: Let's go home and relax after a long day.",
"go into sth: She went into the store to buy some groceries.",
"- *She went into her room*.",
"good at sth: He is really good at playing the piano.",
"good for sb/sth: Eating fruits and vegetables is good for your health.",
"Good morning: Good morning! How are you today?",
"Good afternoon: Good afternoon! How's your day going?",
"Good evening: Good evening, everyone! Welcome to the party.",
"good news: I have some good news to share with you.",
"good thing: It's a good thing you remembered to bring an umbrella; it's raining outside.",
"the good things about sth: One of the good things about living in the countryside is the fresh air.",
"go out: Let's go out for dinner tonight.",
"go to bed: It's getting late; time to go to bed.","go to school: Children go to school to learn new things.",
"go to work: I have to go to work early tomorrow morning.",
"grow up: When I grow up, I want to be a firefighter.",
"Guess what…: Guess what! I got a promotion at work.",
"half an hour: The meeting will start in half an hour.",
"hard work: Success requires dedication and hard work.",
"have fun: I hope you have fun at the party tonight.",
"have got: I have got a new job opportunity.",
"have time: Do you have time to grab a coffee?",
"have time for sth: I always make sure to have time for my hobbies.",
"have time to do sth: I don't have time to finish this project before the deadline.",
"he or she: If anyone needs help, he or she can ask me.",
"high school: She graduated from high school last year.",
"his or her: Each student should bring his or her textbook to class.",
"How about…?: How about we go for a hike this weekend?",
"How are you?: I'm doing well, thank you for asking. How about you?",
"How long…?: How long does it take to get to the airport from here?",
"How many…?: How many people are coming to the party?",
"How much…?: How much does this shirt cost?",
"How often…?: How often do you go to the gym?",
"important for sb/sth: Regular exercise is important for maintaining good health.",
"It is important for sb/sth to do sth: It is important for children to eat a balanced diet for their growth.",
"I’m sorry: I'm sorry for the mistake I made.",
"in April: My birthday is in April.",
"in July, etc.: We usually go on vacation in July.",
"in bed: I like to read a book in bed before going to sleep.",
"in class: Pay attention in class and take notes.",
"in fact: In fact, I've never been to Europe.",
"in front of: Please stand in front of the whiteboard.",
"in my opinion: In my opinion, this is the best restaurant in town.",
"in school: I learned a lot of new things in school today.",
"in space: Astronauts experience weightlessness in space.",
"in summer: I enjoy swimming in the lake in summer.",
"in winter: We like to go skiing in winter.",
"in the centre: The museum is located in the center of the city.",
"in the centre of sth: The hotel is situated in the center of town.",
"in the country: They have a beautiful house in the country.",
"the best… in the country: This restaurant is known as the best in the country.",
"in the future: In the future, I hope to travel around the world.",
"in the morning: I usually have breakfast in the morning before work.",
"in the afternoon: Let's meet for coffee in the afternoon.",
"in the evening: I like to relax with a book in the evening.",
"in the north: The weather is colder in the north.",
"in the south: The south of the country is known for its warm climate.",
"in the east: The sun rises in the east.",
"in the west: The mountains are located in the west.",
"in the past: In the past, people used to communicate by writing letters.",
"in the street: There's a lot of traffic in the street today.",
"in the summer: We love to go hiking in the summer.",
"in the winter: I prefer to stay indoors in the winter.",
"in town: Let's meet for lunch in town.",
"it is important to do sth: It is important to eat a balanced diet for good health.",
"It takes…: It takes an hour to get there by car.",
"- *It takes an hour to get there*.",
"kind of sb/sth: What kind of books do you enjoy reading?",
"What kind of music do you like?: I like all kinds of music, from classical to pop.",
"know how: I know how to play the piano.",
"know how to do sth: Do you know how to cook spaghetti?",
"last time: The last time I saw her was at the party.",
"the last time: That was the last time I'll ever try skydiving!",
"last year: We went on a trip to Europe last year.",
"last month: I visited my parents last month.",
"last summer: We went camping in the mountains last summer.",
"last week: I met with my friends for dinner last week.",
"last weekend: We went to the beach last weekend.",
"learn how to do sth: I want to learn how to speak French.",
"listen to sb/sth: I like to listen to music while I work.",
"live with sb: I live with my family in a small apartment.",
"living room: Let's sit in the living room and watch a movie.",
"look at sb/sth: Look at that beautiful sunset!",
"look for sb/sth: I need to look for my keys; I can't find them anywhere.",
"look like sb/sth: She looks like her mother.",
"lots of…: There are lots of books on the shelf.",
"millions of…: Millions of people visit the city every year.",
"mobile phone: Don't forget to bring your mobile phone with you.",
"more than…: There's more than one way to solve this problem.",
"next time: Next time, let's plan a trip together.",
"next year: I plan to travel to Europe next year.",
"next month: Next month, I'm starting a new job.",
"next week: Let's have dinner together next week.",
"No problem: Thank you for your help. No problem, happy to assist.",
"of course: Can you help me with this? Of course, I'd be happy to help.",
"Oh no!: Oh no! I forgot to bring my umbrella, and now it's raining.",
"Oh yes: Oh yes, I remember that place; it was beautiful.",
"old friend: I bumped into an old friend from college yesterday.",
"once a…: I go to the gym once a week to stay fit.",
"once a month: I treat myself to a massage once a month.",
"once a week: They have a family dinner once a week.",
"once a year: We have a family reunion once a year.",
"one day: One day, I hope to travel around the world.",
"on holiday: I'll be on holiday next week, so I won't be available.",
"on Monday: We have a meeting scheduled on Monday.",
"on Tuesday, etc.: The event is happening on Tuesday, so don't forget to mark your calendar.",
"on television: I saw your favorite singer on television last night.",
"on the television: There's a great movie on the television right now.",
"on the beach: Let's have a picnic on the beach this weekend.",
"on the floor: I found my keys on the floor next to the couch.",
"on the internet: You can find all kinds of information on the internet.",
"on the left: Turn left at the traffic light.",
"on the right: The restaurant is on the right side of the street.",
"on the phone: I'll talk to him on the phone later.",
"be on the phone: Sorry, I can't talk right now; I'm on the phone.",
"talk on the phone: I need to talk on the phone with my friend to make plans.",
"on TV: Did you see that commercial on TV last night?",
"out of sth: We're out of milk; I need to buy some more.",
"over there: Look, your keys are over there on the table.",
"pay for sth: How much did you have to pay for the concert tickets?",
"phone call: I received a phone call from my mom this morning.",
"phone number: Can I have your phone number so I can reach you?",
"plan for sth: We need to plan for the upcoming project.",
"make plans for sth: Let's make plans for our vacation next year.","What are your plans for next year?",
"play with sb/sth: My son loves to play with his toys.",
"post office: I need to mail this package; I'll go to the post office later.",
"pretty good: How was the movie? It was pretty good.",
"really enjoy: I really enjoyed the concert last night.",
"really good: The food at that restaurant is really good.",
"really like: I really like your new haircut.",
"I’d really like to…: I'd really like to go hiking this weekend.",
"right now: I'm busy right now, but I'll call you back later.",
"See you: See you tomorrow at the party.",
"See you around: I'll see you around the neighborhood.",
"See you later: See you later; have a great day!",
"See you soon: I'll see you soon; take care.",
"sit down: Please sit down and make yourself comfortable.",
"someone else: Someone else already took the last slice of pizza.",
"something else: I forgot my book at home; I'll have to read something else.",
"speak to sb: I need to speak to my boss about my upcoming project.",
"spend time: It's important to spend time with family.",
"spend time doing sth: I like to spend time reading books in the evening.",
"spend time with sb: I enjoy spending time with my friends on the weekends.",
"stand up: Please stand up and introduce yourself.",
"stay in: I'm feeling tired tonight, so I'll stay in and watch a movie.",
"stay in a hotel: We decided to stay in a hotel instead of camping.",
"stay in bed: I'm not feeling well, so I'm going to stay in bed today.",
"such as: There are many fruits, such as apples, bananas, and oranges.",
"swimming pool: Let's go to the swimming pool and cool off.",
"talk about sb/sth: We need to talk about the upcoming project.",
"thank you: Thank you for your help; I appreciate it.",
"thank you very much: Thank you very much for the lovely gift.",
"that day: I'll never forget what happened on that day.",
"the 20th century: The industrial revolution took place in the 19th and 20th centuries.",
"the 21st century: We are currently living in the 21st century.",
"the 19th century: Many significant historical events occurred in the 19th century.",
"the next day: The weather was much better the next day.",
"there is: There is a cat on the roof.",
"there are: There are many people waiting for the bus.",
"there was: There was a big party at the neighbor's house last night.",
"there were: There were three puppies playing in the yard.",
"think about sb/sth: I often think about my future goals and aspirations.",
"think of sb/sth: What do you think of the new restaurant in town?",
"This is…: This is my best friend, Sarah.",
"this kind of…: I like this kind of music; it's relaxing.",
"this morning: I had pancakes for breakfast this morning.",
"this afternoon: Let's go for a walk this afternoon.",
"this evening: We're going out for dinner this evening.",
"this time: I'll get it right this time.",
"this year: I'm planning a trip to Europe later this year.",
"this summer: I'm planning to go on a road trip this summer.",
"this weekend: Let's go hiking in the mountains this weekend.",
"thousands of…: There are thousands of stars visible in the night sky.",
"too long: The line at the grocery store is too long; let's go somewhere else.",
"too far: The nearest gas station is too far; we need to fill up the tank.",
"too hard: This math problem is too hard for me to solve.",
"too much: You've eaten too much cake; you might get a stomach ache.",
"too many: There are too many cars on the road during rush hour.",
"town centre: Let's meet at the café in the town center.",
"in the town centre: The new library is located right in the town center.",
"TV show: I enjoy watching my favorite TV show every Sunday.",
"wait for sb/sth: Please wait for me; I'll be there in a minute.",
"wake up: I usually wake up at 7 a.m. during the weekdays.",
"welcome to sth: Welcome to our new office space; we hope you feel at home.",
"What about…?: What about going to the beach for our vacation?",
"work as sth: She works as a teacher at the local school.",
"work for sb/sth: I work for a software company in the marketing department.",
"work hard: If you want to succeed, you need to work hard.",
"work together: Let's work together to solve this problem.",
"work together for sth: We need to work together for the success of the project.",
"work together to do sth: We worked together to organize the charity event.",
"work with sb: I enjoy working with my colleagues; we make a great team.",
"would like: I would like a cup of coffee, please.",
"I would like…: I would like to order the steak for dinner.",
"I would like to…: I would like to go on a vacation to Europe next summer.",
"Would you like…?: Would you like some tea or coffee?",
"X hours a day: I work eight hours a day, five days a week.",
"X times a…: I go to the gym three times a week.",
"X times a day: I take my medication three times a day.",
"X times a week: They meet for tennis practice four times a week.",
"X years ago: I visited Paris for the first time five years ago.",
"X days ago: We went on a hiking trip three days ago.",
"X months ago: I started my new job six months ago.",
"X weeks ago: We moved into our new house two weeks ago.",
"X years later: Ten years later, they were still happily married.",
"X days later: Three days later, the package arrived in the mail.",
"X minutes later: Twenty minutes later, he finally arrived.",
"X years old: My grandfather is eighty years old.",
"You’re welcome: Thank you for your help." "You're welcome, anytime.",
"a bit: Can you speak a bit louder, please?",
"able to do sth: She is able to speak three languages fluently.",
"a couple of sth: I bought a couple of books at the bookstore.",
"add to sth: Let's add some sugar to the coffee.",
"again and again: He kept making the same mistake again and again.",
"all about…: This book is all about dinosaurs.",
"Tell me all about it.",
"all kinds of…: The store sells all kinds of candies.",
"all over…: There were clothes strewn all over the bedroom floor.",
"all over the world: The internet connects people from all over the world.",
"all sorts of…: We saw all sorts of animals at the zoo.",
"all the time: She talks on the phone all the time.",
"a long time ago: Dinosaurs lived a long time ago.",
"a long way: We've come a long way since we started this project.",
"a number of sth: A number of students attended the lecture.",
"a large number of sth: A large number of people showed up for the event.",
"apply for sth: She decided to apply for a job at the company.",
"art gallery: Let's visit the art gallery downtown.",
"as a result: He failed the exam, and as a result, he had to retake the course.",
"as a result of sth: She lost her job as a result of the company's downsizing.",
"as part of sth: He joined the company as part of the marketing team.",
"as part of a team: We worked together as part of a team to complete the project.",
"as soon as: I'll call you as soon as I finish work.",
"as well: She speaks French fluently, as well as Spanish.",
"as well as sb/sth: The party included adults as well as children.",
"at first: At first, I didn't like the idea, but now I'm warming up to it.",
"at least: You should drink at least eight glasses of water a day.",
"at the age of…: He started working at the age of sixteen.",
"at the start of sth: At the start of the movie, the protagonist faces a challenge.",
"at the time: At the time, I didn't realize how important it was.",
"at that time: At that time, we were living in a small apartment.",
"at the time of sth: He was living in Paris at the time of the revolution.",
"at the top: She's at the top of her class.",
"at the top of sth: There's a flag flying at the top of the mountain.",
"based on sth: The decision was based on careful consideration of all the facts.",
"be allowed to do sth: Students are allowed to bring calculators to the exam.",
"believe in sb/sth: I believe in you; you can do it.",
"belong to sb: This book belongs to my sister.",
"belong to sth: The keys belong to the car.",
"be made of sth: The table is made of wood.",
"by the end of sth: I want to finish reading this book by the end of the week.",
"care about sth: She cares deeply about the environment.",
"carry on: Let's carry on with our discussion.",
"carry on with sth: Let's carry on with our discussion about the project.",
"carry sth out: We need to carry out the plan as soon as possible.",
"check in: Don't forget to check in at the hotel when you arrive.",
"check in at…: We need to check in at the airport two hours before our flight.",
"check sth in: Make sure to check your luggage in before boarding.",
"check out: We checked out of the hotel early in the morning.",
"check out of sth: We checked out of the Airbnb after a wonderful stay.",
"climate change: Climate change is a pressing issue that affects us all.",
"close to sb/sth: The park is close to our house.",
"come back: When will you come back from your trip?",
"Come on!: Come on, let's go for a walk in the park.",
"connected to sth: My phone is connected to the Wi-Fi network.",
"connected with sb/sth: She feels connected with nature when she hikes.",
"credit card: I paid for the groceries with my credit card.",
"deal with sb: She knows how to deal with difficult customers.",
"deal with sth: We need to deal with this problem before it gets worse.",
"depend on sb/sth: We depend on the weather for our outdoor plans.",
"depend on sb/sth for sth: We depend on our parents for financial support.",
"depend on sth: Success depends on hard work and determination.",
"do well: I hope you do well on your exam.",
"each one: Each one of these books is a classic.",
"end with sth: The concert ended with a spectacular fireworks display.",
"even more…: She became even more determined to succeed.",
"even more difficult: The final exam was even more difficult than we expected.",
"even more exciting: The trip became even more exciting when we spotted a rare bird.",
"everyone else: Everyone else had already left the party when we arrived.",
"except for: Everyone went to the beach except for Sarah.",
"fall in love: They fell in love while traveling through Europe.",
"fall in love with sb: I fell in love with him the moment I met him.",
"fall off: Be careful not to fall off the ladder.",
"fall off sth: The picture fell off the wall during the earthquake.",
"far away: The nearest gas station is far away from here.",
"feel good: Exercising regularly makes me feel good.",
"feel like sth: Do you feel like going for a walk in the park?",
"fill sth in: Please fill in the form with your personal details.",
"find it difficult to do sth: Some people find it difficult to adapt to change.",
"first of all: First of all, let me introduce myself.",
"followed by sb/sth: The meeting was followed by a team-building exercise.",
"for the rest of sth: She decided to stay in bed for the rest of the day.",
"for this reason: For this reason, we need to take action to address the issue.",
"get back: I need to get back to work after my lunch break.",
"get better: I hope you get better soon; take care of yourself.",
"get lost: He got lost in the forest while hiking.",
"get out: Let's get out of the house and enjoy the sunshine.",
"get out of sth: He managed to get out of attending the meeting by feigning illness.",
"give up: Don't give up on your dreams; keep striving for success.",
"give sth up: She decided to give up sugar for a healthier lifestyle.",
"go and…: I need to go and pick up my dry cleaning.",
"go and get help: Quick, go and get help; there's been an accident.",
"go away: The stray cat refused to go away from our doorstep.",
"go down: Prices are going down due to increased competition.",
"Prices are going down.",
"go down sth: Let's go down the stairs to the basement.",
"Go down the road: Go down the road and turn left at the traffic light.",
"go for sth: I think I'll go for the chicken salad for lunch.",
"go for a walk: Let's go for a walk in the park this evening.",
"go up: Prices are going up due to inflation.",
"Prices are going up.",
"good luck: Good luck on your job interview; I'm sure you'll do great.",
"happen to sb/sth: Accidents can happen to anyone, so always be cautious.",
"happy with sb/sth: She's happy with her new job; it's a perfect fit for her.",
"have a look: Let's have a look at the new apartment this afternoon.",
"have a look at sth: Have a look at this beautiful sunset.",
"have got to: I have got to finish this report before the deadline.",
"Have you ever…?: Have you ever traveled to Asia?",
"health problems: Smoking can lead to serious health problems.",
"hear about sb/sth: I heard about your promotion; congratulations!",
"I don’t care: I don't care what they say; I'm going to follow my own path.",
"if necessary: We'll call for help if necessary.",
"if you want to: Feel free to join us for dinner if you want to.",
"I guess: I guess we'll have to postpone the meeting until next week.",
"I’m afraid…: I'm afraid I won't be able to attend the party; I have a prior commitment.",
"I mean: By 'vacation,' I mean a trip to a tropical island.",
"in business: He's been in business for over 20 years.",
"in danger: The hikers were in danger of getting caught in the storm.",
"in history: This is the largest earthquake recorded in history.",
"the first time in history: This is the first time in history that humans have traveled to Mars.",
"in hospital: He's currently in hospital recovering from surgery.",
"in love: She's head over heels in love with her new boyfriend.",
"in love with sb: I'm in love with you; will you marry me?",
"in prison: He spent five years in prison for his crimes.",
"in some cases: In some cases, surgery may be necessary to treat the condition.",
"instead of: I'll have tea instead of coffee, please.",
"in the air: The smell of freshly baked cookies was in the air.",
"in the end: In the end, they decided to go with option B.",
"in the middle: She sat in the middle of the row during the movie.",
"in the middle of sth: We were interrupted in the middle of our conversation.",
"in the same way: He approached the problem in the same way as before.",
"in this way: By saving money each month, you can build up your savings in this way.",
"it depends: Whether we go camping this weekend depends on the weather.",
"it all depends: Whether we win the game or not—it all depends on our teamwork.",
"I think so: 'Are you coming to the party?' 'Yes, I think so.'",
"I don’t think so: 'Will it rain tomorrow?' 'I don’t think so, the sky looks clear.'",
"lead to sth: Poor communication can lead to misunderstandings.",
"less than…: The price of the jacket is less than $50.",
"Let me…: Let me open the door for you.",
"Let me help you.",
"let me know: If you need any help, just let me know.",
"look after sb/sth/yourself: She looks after her younger siblings after school.",
"look back at sth: Let's look back at the progress we've made this year.",
"Look back at your notes.",
"look sth up: If you're not sure, you can look it up in the dictionary.",
"make a mistake: Don't worry if you make a mistake; it's all part of learning.",
"make money: He started a business to make money.",
"make sense: Your explanation makes sense; thank you.",
"make sure: Make sure to lock the door before you leave.",
"make sure of sth: He wanted to make sure of his facts before presenting the report.",
"make sure that…: Make sure that you have all the necessary documents before traveling.",
"much better: After resting, I feel much better.",
"not at all: 'Thank you for your help.' 'Not at all, happy to assist.'",
"I didn’t enjoy it at all: I didn’t enjoy the movie at all; it was quite boring.",
"no way: 'Are you going to jump off the cliff?' 'No way, that's too dangerous!'",
"No way!: 'I just won the lottery!' 'No way! That's amazing!'",
"There is no way (that)…: There is no way that I'm going to eat that; it looks disgusting.",
"Oh well: Oh well, I guess we'll have to try again tomorrow.",
"on earth: How on earth did you manage to finish that project so quickly?",
"on the ground: The dog was lying on the ground, enjoying the sunshine.",
"on the other side: The store is on the other side of the street.",
"on the other side of sth: The hotel is on the other side of the river.",
"on the wall: Hang the picture on the wall, please.",
"on time: The train arrived on time.",
"on top of sth/sb: The cat sat on top of the refrigerator.",
"one or two: Just add one or two more tablespoons of sugar to the recipe.",
"ordinary people: The event was attended by ordinary people from all walks of life.",
"pay attention: Pay attention in class so you don't miss important information.",
"pay attention to sb/sth: He paid close attention to the details of the painting.",
"per hour: He earns $20 per hour at his part-time job.",
"kilometres per hour: The speed limit on this road is 60 kilometers per hour.",
"miles per hour: Cars on the highway often travel at speeds exceeding 70 miles per hour.",
"pick sb/sth up: Can you pick me up from the airport tomorrow?",
"police officer: The police officer directed traffic during the parade.",
"police station: She reported the theft to the police station downtown.",
"public transport: Many people use public transport to commute to work.",
"put sth on: Put on your coat; it's cold outside.",
"quite a lot: She earns quite a lot of money from her online business.",
"quite a lot of sth: We have quite a lot of work to do before the deadline.",
"reasons why: He listed several reasons why he believed the project would succeed.",
"refer to sb/sth: Can you refer me to a good mechanic?",
"refer to sb/sth as sth: She always refers to her dog as her 'furry child.'",
"report on sth: The journalist filed a report on the recent protests.",
"respond to sth/sb: He responded to the email immediately.",
"save money: I try to save money by cooking meals at home instead of eating out.",
"science fiction: 'Star Wars' is a classic example of science fiction.",
"search for sth/sb: They went out to search for the missing hiker.",
"so that…: He studied hard so that he could get good grades.",
"solution to sth: We need to find a solution to the problem before it gets worse.",
"sort of sth: That's not the sort of behavior we expect from you.",
"What sorts of things do you do?: I enjoy reading, hiking, and painting. What sorts of things do you do?",
"sound like sb/sth: Your explanation sounds like a plausible solution.",
"start with sb/sth: Let's start with the basics and then work our way up.",
"such a/an…: She's such a talented musician.",
"such a good idea: Going for a hike this weekend is such a good idea.",
"take care of sb/sth/yourself: I'll take care of the children while you're out.",
"take off: The plane will take off in ten minutes.",
"take sth off: Take off your shoes before entering the house.",
"take part: Are you planning to take part in the charity run?",
"take part in sth: She took part in the school play last year.",
"take place: The concert will take place in the park next Saturday.",
"the best thing: Eating healthy and exercising regularly is the best thing you can do for your health.",
"the best thing to do: If you're feeling stressed, the best thing to do is to take a break and relax.",
];